config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get 'pages/home', to: 'pages#home'
   
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  
  resources :incredients, except:[:destroy]
  
  mount ActionCable.server => '/cable'
  
end

app/models/incredient.rb
class Incredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_incredients
  has_many :recipes, through: :recipe_incredients
end

app/controllers/incredients_controller.rb
class IncredientsController < ApplicationController
  before_action :set_incredient, only: [:edit, :update, :show]
   before_action :require_admin, except: [:show, :index]
  def new
    @incredient = Incredient.new
  end
  
  def create
    @incredient = Incredient.new(incredient_params)
    if @incredient.save
      flash[:success] = "Ingredient was successfully created"
      redirect_to incredient_path(@incredient)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
      if @incredient.update(incredient_params)
      flash[:success] = "Ingredient name was updated successfully"
      redirect_to @incredient
    else
      render 'edit'
      end
  end
  
  def show
    @incredient_recipes = @incredient.recipes.paginate(page: params[:page], per_page: 5)
  end
  
  def index
    @incredients = Incredient.paginate(page: params[:page],per_page: 5)
  end
  
  private
  
   def incredient_params
    params.require(:incredient).permit(:name)
   end
  
  def set_incredient
    @incredient= Incredient.find(params[:id])
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to incredients_path
    end
  end
  
end

app/views/incredients/_form.html.erb
<%= render 'shared/errors', obj: @incredient%>
<div class ="row">
 <div class="col-md-12">
    <%= form_for(@incredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class= "form-group">
        <div class= "control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class= "col-md-8">
           <%= f.text_field :name , class: "form-control", placeholder: "Enter incredient" , autofocus:true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-8">
         <%= f.submit(@incredient.new_record? ? "Add Incredient" : "Update Incredient", class:"btn btn-primary btn-lg btn-xlarge") %> 
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing ", recipes_path %>]
    </div>
  </div>
</div>

app/views/incredients/_incredient.html.erb
<span class="badge"><%= link_to incredient.name, incredient_path(incredient)%> &nbsp;</span>

app/views/incredients/edit.html.erb
<%= render 'shared/page_title', title: "edit ingredient name " %>

<%=render 'form'%>

app/views/incredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<div align="center">
  <%= will_paginate %>
  <% @incredients.each do |ing| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="chef-title"><%= link_to ing.name.capitalize,incredient_path(ing) %></li>
          <li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>
          
          <% if logged_in? && current_chef.admin? %>
            <li><%= link_to "Edit this ingredient", edit_incredient_path(ing) %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/incredients/new.html.erb
<%= render 'shared/page_title', title: "enter a new ingredient" %>

<%=render 'form'%>

app/views/incredients/show.html.erb
<%= render 'shared/page_title', title: "#{@incredient.name} " %>
<% if @incredient.recipes.count != 0  %>
  <h4 align="center">Recipe's containing <%= @incredient.name %></h4>
  <div align="center">
     <%= will_paginate @incredient_recipes%>
  </div>
     <%= render 'recipes/recipe', obj: @incredient_recipes %>
  <div align="center">
     <%= will_paginate @incredient_recipes%>
  </div>
<% else %>
  <h4 align = "center"> No recipes yet!</h4>
<% end %>